import * as store from './store.js';

const now = Date.now();
const demo = [
  {
    message_id: 'om_demo_001',
    chat_id: 'oc_demo_group_a',
    chat_type: 'group',
    message_type: 'text',
    content_text: '明天下午三点会议室改到 B2，别走错了',
    content_raw: JSON.stringify({ text: '明天下午三点会议室改到 B2，别走错了' }),
    sender_id: 'ou_alice',
    sender_name: 'Alice',
    sender_type: 'user',
    create_time: String(now - 3600_000),
    recalled: true,
    recall_time: String(now - 3500_000),
    recall_type: 'message_owner',
    created_at: now - 3600_000,
    updated_at: now - 3500_000,
  },
  {
    message_id: 'om_demo_002',
    chat_id: 'oc_demo_group_a',
    chat_type: 'group',
    message_type: 'text',
    content_text: '密码先用 Temp#2026，上线前再换',
    content_raw: JSON.stringify({ text: '密码先用 Temp#2026，上线前再换' }),
    sender_id: 'ou_bob',
    sender_name: 'Bob',
    sender_type: 'user',
    create_time: String(now - 7200_000),
    recalled: true,
    recall_time: String(now - 7000_000),
    recall_type: 'group_manager',
    created_at: now - 7200_000,
    updated_at: now - 7000_000,
  },
  {
    message_id: 'om_demo_003',
    chat_id: 'oc_demo_p2p',
    chat_type: 'p2p',
    message_type: 'post',
    content_text: '周报\n1. 完成飞书撤回查看器原型\n2. 待联调开放平台事件',
    content_raw: JSON.stringify({
      zh_cn: {
        title: '周报',
        content: [[{ tag: 'text', text: '1. 完成飞书撤回查看器原型' }], [{ tag: 'text', text: '2. 待联调开放平台事件' }]],
      },
    }),
    sender_id: 'ou_carol',
    sender_name: 'Carol',
    sender_type: 'user',
    create_time: String(now - 1800_000),
    recalled: true,
    recall_time: String(now - 1700_000),
    recall_type: 'message_owner',
    created_at: now - 1800_000,
    updated_at: now - 1700_000,
  },
  {
    message_id: 'om_demo_004',
    chat_id: 'oc_demo_group_b',
    chat_type: 'group',
    message_type: 'image',
    content_text: '[图片] img_v2_demo_key',
    content_raw: JSON.stringify({ image_key: 'img_v2_demo_key' }),
    sender_id: 'ou_dave',
    sender_name: 'Dave',
    sender_type: 'user',
    create_time: String(now - 900_000),
    recalled: true,
    recall_time: String(now - 800_000),
    recall_type: 'group_owner',
    created_at: now - 900_000,
    updated_at: now - 800_000,
  },
  {
    message_id: 'om_demo_005',
    chat_id: 'oc_demo_group_a',
    chat_type: 'group',
    message_type: 'text',
    content_text: '这条还没撤回，只是普通消息',
    content_raw: JSON.stringify({ text: '这条还没撤回，只是普通消息' }),
    sender_id: 'ou_alice',
    sender_name: 'Alice',
    sender_type: 'user',
    create_time: String(now - 300_000),
    recalled: false,
    created_at: now - 300_000,
    updated_at: now - 300_000,
  },
];

store.replaceAll(demo);
console.log(`[seed] 写入 ${demo.length} 条演示数据（其中撤回 ${demo.filter((m) => m.recalled).length} 条）`);
